[theme]
base = "light"
primaryColor = "#E0692A"
backgroundColor = "#FAF7F0"
secondaryBackgroundColor = "#FFFCF6"
textColor = "#1F1A14"
font = "sans serif"


[browser]
gatherUsageStats = false

[server]
fileWatcherType = "watchdog"
runOnSave = true

